version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  api:
    build:
      context: ./apps/api/
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
    - ./apps/api/:/usr/app
    - /usr/app/node_modules
    depends_on:
      - mongo
    links:
      - mongo
  web:
    build:
      context: ./apps/web/
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - api
